---

- name: check bandwhich releases
  uri:
    url: https://api.github.com/repos/imsnif/bandwhich/releases/latest
    return_content: yes
  register: releases

- name: check if bandwhich is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/bandwhich
  register: bandwhich_stat

- name: check local bandwhich version
  ansible.builtin.command: /usr/local/bin/bandwhich version
  register: bandwhich_version
  when:
  - bandwhich_stat.stat.exists
  - false
  changed_when: false

- name: download bandwhich {{ releases.json.tag_name }}
  become: true
  ansible.builtin.unarchive:
    src: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `linux`) && contains(name, `gnu`)].browser_download_url | [0]') }}"
    remote_src: true
    dest: /usr/local/bin/
  diff: false
  when:
    - not ansible_check_mode
    # - not bandwhich_stat.stat.exists or (releases.json.tag_name[1:] not in bandwhich_version.stdout_lines[0])
