---

- name: install common packages
  become: true
  ansible.builtin.apt:
    name:
    - ack
    - apt-file
    - apt-transport-https
    - byobu
    - cups
    - cups-client
    - curl
    - dnsutils
    - flameshot
    - git
    - git-lfs
    - gpg
    - gpg-agent
    - hcloud-cli
    - htop
    - iftop
    - ipcalc
    - iptraf
    - iptraf-ng
    - keychain
    - libnotify-bin
    - man
    - mtr
    - neovim
    - net-tools
    - nethogs
    - ocrmypdf
    - tesseract-ocr-fra
    - oathtool
    - openssh-client
    - openssh-server
    - openssl
    - paperkey
    - pass
    - pass-extension-otp
    - pigz
    - pssh
    - pwgen
    - qpdf
    - qrencode
    - scdaemon
    - screenfetch
    - sudo
    - tmate
    - uuid
    - wget
    - whois
    - wireguard-tools
    - xz-utils
    - yt-dlp
    - yubikey-manager
    - yubikey-personalization
    - zbar-tools

- name: remove extra packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages_absent_extra | join(',') }}"
    state: absent
  when: packages_absent_extra is defined

- name: install extra packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages_extra | join(',') }}"
  when: packages_extra is defined
