---
all:
  children:
    private:
      hosts:
        play:
        x1:
    work:
      hosts:
        LAP-CH-390-LIN:
        LAP-CH-541-LIN:
  vars:
    ansible_python_interpreter: /usr/bin/python3
