---
all:
  children:
    private:
      hosts:
        play:
        x1:
    work:
      hosts:
        LAP-CH-541-LIN:
        LAP-CH-553-LIN:
          # ansible_host:
          # ansible_user:
          # ansible_connection: ssh
  vars:
    ansible_python_interpreter: /usr/bin/python3
