[project]
name = "laptop-ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.1.0",
    "jmespath>=1.0.1",
]
