# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Display help when no argument is given to task
    cmds:
      - task: help
        silent: true

  help:
    desc: List all available tasks (default)
    cmds:
      - task --list-all

  local:
    desc: run ansible playbook on this local host
    cmds:
      - uv run ./update-local.sh {{.CLI_ARGS}}

  lock:
    desc: perform a uv lock
    cmds:
      - uv lock

  rebuild:
    desc: rebuild the uv environment
    cmds:
      - rm -rf .venv
      - task: sync

  sync:
    desc: perform a uv sync
    cmds:
      - uv sync

  vault-edit:
    desc: perform an Ansible vault command
    cmds:
      - uv run ansible-vault edit {{.CLI_ARGS}}
