# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Display help when no argument is given to task
    cmds:
      - task: help
        silent: true

  fix-pipx:
    desc: Fix pipx standard problem with a reinstall-all
    cmds:
      - pipx reinstall-all

  help:
    desc: List all available tasks (default)
    cmds:
      - task --list-all

  local:
    desc: run ansible playbook on this local host
    cmds:
      - pipenv run ./update-local.sh {{.CLI_ARGS}}

  lock:
    desc: perform a pipenv lock
    cmds:
      - pipenv lock

  rebuild:
    desc: rebuild the pipenv environment
    cmds:
      - rm -rf .venv
      - task: sync

  sync:
    desc: perform a pipenv sync
    cmds:
      - pipenv sync

  vault-edit:
    desc: perform an Ansible vault command
    cmds:
      - pipenv run ansible-vault edit {{.CLI_ARGS}}
