---

- name: check home directory for {{ username }}
  become: true
  stat:
    path: "/home/{{ username }}"
    get_checksum: no
  register: user_home
  tags: system, root

- name: prompting for {{ username }} password if needed
  pause:
    prompt: "Give a password for {{ username }}"
    echo: no
  when: not user_home.stat.exists
  register: user_password
  tags: system, root

- name: set user {{ username }} password
  become: true
  user:
    name: "{{ username }}"
    state: present
    password: "{{ user_password.user_input |password_hash('sha512') }}"
    update_password: on_create
  when: not user_home.stat.exists
  tags: system, root

- name: verify user configuration
  become: true
  user:
    name: "{{ username }}"
    state: present
    append: true
    groups:
      - audio
      - bluetooth
      - cdrom
      - dip
      - floppy
      - plugdev
      - netdev
      - video
  tags: user, root

- name: change home permissions for {{ username }}
  become: true
  become_user: "{{ username }}"
  file:
    path: "~/"
    state: directory
    mode: 0750
  tags: user

- name: create directory for ansible remote_tmp to skip warning
  become: true
  become_user: "{{ username }}"
  file:
    path: "~/.ansible/tmp"
    state: directory
    mode: 0750
  tags: user

- name: create directories
  become: true
  become_user: "{{ username }}"
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode|default('') }}"
  loop:
    - path: "~/.config"
    - path: "~/.config/dunst"
    - path: "~/.config/nvim"
    - path: "~/.config/pypoetry"
    - path: "~/.config/systemd/user"
    - path: "~/.config/tmux"
    - path: "~/Private"
    - path: "{{ packages_directory }}"
    - path: "~/.ssh"
      mode: "0700"
    - path: "~/.ssh/socket"
      mode: "0700"
    - path: "{{ code_directory }}"
    - path: "~/bin"
  tags: user
