---

- name: install poetry through pipx
  become: true
  become_user: "{{ username }}"
  community.general.pipx:
    name: poetry

- name: create poetry configuration directory
  become: true
  become_user: "{{ username }}"
  file:
    path: "~/.config/pypoetry"
    state: directory

- name: install poetry configuration files
  become: true
  become_user: "{{ username }}"
  template:
    src: pypoetry.config.toml
    dest: ~/.config/pypoetry/config.toml
    mode: '0644'