---

- name: add repository GPG key for Sublime
  become: true
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/trusted.gpg.d/sublime.gpg
  when: ansible_os_family == "Debian"

- name: add repository for Sublime
  become: true
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/sublime.gpg] https://download.sublimetext.com/ apt/stable/
  when: ansible_os_family == "Debian"

- name: install Sublime
  become: true
  apt:
    pkg: sublime-text

- name: create sublime config directory
  become: true
  become_user: "{{ username }}"
  file:
    path: "~/.config/sublime-text-3/Packages/User"
    state: directory
  when: ansible_facts.packages['sublime-text'] is defined

- name: configure sublime preferences
  become: true
  become_user: "{{ username }}"
  template:
    src: Preferences.sublime-settings.j2
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  when: ansible_facts.packages['sublime-text'] is defined
