---

- name: install development toolbox packages
  become: yes
  ansible.builtin.apt:
    name:
    - automake
    - build-essential
    - cmake
    - default-mysql-client
    - git
    - gpg
    - gpg-agent
    - jq
    - kafkacat
    - libbz2-dev
    - libmariadbclient-dev-compat
    - libncurses5-dev
    - libncursesw5-dev
    - libqt5sql5-mysql
    - libqt5sql5-psql
    - libqt5sql5-sqlite
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - llvm
    - make
    - postgresql-client
    - qtbase5-dev
    - qttools5-dev-tools
    - tidy
    - zlib1g-dev
