---
# Moved to terraform-switcher instead

- name: clear tfenv
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "~/.tfenv"
    state: absent

- name: clear hashicorp configuration directory
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "{{ config.zsh }}/hashicorp"
    state: absent

- name: clear hashicorp terraform module-plugins shared directory
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "~/.terraform.d/plugins"
    state: absent