---

- name: install i3 packages
  become: true
  package:
    pkg: "{{ item }}"
  with_together:
    - i3
    - i3blocks
    - i3status
    - i3lock
    - fonts-powerline
    - powerline

- name: configure a i3lock on sleep
  become: true
  template:
    src: i3lock-sleep.service.j2
    dest: /etc/systemd/system/i3lock-sleep@.service

- name: create i3 config directory
  become: true
  become_user: "{{ username }}"
  file:
    path: "~/.config/i3"
    state: directory

- name: configure i3
  become: true
  become_user: "{{ username }}"
  template:
    src: i3-config.j2
    dest: ~/.config/i3/config

- name: configure i3 status
  become: true
  become_user: "{{ username }}"
  template:
    src: i3-status.conf.j2
    dest: ~/.i3status.conf

- name: configure i3blocks
  become: true
  become_user: "{{ username }}"
  template:
    src: i3-blocks.conf.j2
    dest: ~/.i3blocks.conf

- name: enable i3lock on sleep service for {{ username }}
  become: true
  systemd:
    enabled: true
    name: "i3lock-sleep@{{ username }}.service"
    daemon_reload: true
