---

- name: install Debian packages
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - task-desktop
    - task-gnome-desktop
  when: ansible_distribution == "Debian"

- name: install desktop
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - autorandr
    - blueman
    - brightnessctl
    - calibre
    - "chromium{% if ansible_distribution == 'Ubuntu' %}-browser{% endif %}"
    - dictionaries-common
      # - evolution
    - fonts-symbola
    - gimp
    - gocryptfs
    - hunspell-en-us
    - hunspell-fr-modern
    - inkscape
    - libreoffice
    - network-manager
    - network-manager-gnome
    - network-manager-openvpn-gnome
    - network-manager-l2tp-gnome
    - pasystray
    - pavucontrol
    - pulseaudio
    - remmina
    - rdesktop
    - telegram-desktop
    - treesheets
    - vlc
    - suckless-tools
    - x11-xkb-utils
    - xclip
    - xinput
    - xsettingsd

- name: import i3 tasks
  import_tasks: i3.yml

- name: import xfce4 tasks
  import_tasks: xfce.yml
