---

- name: install Debian packages
  become: true
  ansible.builtin.apt:
    name:
    - task-desktop
    - task-gnome-desktop
  when: ansible_distribution == "Debian"

- name: install desktop
  become: true
  ansible.builtin.apt:
    name:
    - autorandr
    - blueman
    - brightnessctl
    - calibre
    - "chromium{% if ansible_distribution == 'Ubuntu' %}-browser{% endif %}"
    - dictionaries-common
    - evolution
    - fonts-symbola
    - gimp
    - gocryptfs
    - hunspell-en-us
    - hunspell-fr-revised
    - inkscape
    - libreoffice
    - lxappearance
    - network-manager
    - network-manager-gnome
    - pasystray
    - pavucontrol
    - rdesktop
    - telegram-desktop
    - treesheets
    - vlc
    - suckless-tools
    - x11-xkb-utils
    - xclip
    - xinput
    - xsettingsd

- name: configure xorg rules
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/X11/xorg.conf.d/{{ item.dest }}"
    mode: 0644
  loop:
#    - src: 00-keyboard.conf.j2
#      dest: 00-keyboard.conf
    - src: 30-touchpad.conf.j2
      dest: 30-touchpad.conf
    - src: 31-mouse.conf.j2
      dest: 31-mouse.conf
    - src: 32-mx-ergo.conf.j2
      dest: 32-mx-ergo.conf
    - src: 40-topre-realforce.conf.j2
      dest: 40-topre-realforce.conf
    - src: 40-corne.conf.j2
      dest: 40-corne.conf

- name: dunst configuration
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: dunstrc.j2
    dest: ~/.config/dunst/dunstrc

- name: import i3 tasks
  import_tasks: i3.yml

- name: import xfce4 tasks
  import_tasks: xfce.yml

- name: import kitty tasks
  import_tasks: kitty.yml
