---

- name: install xfce4 terminal
  become: true
  ansible.builtin.apt:
    name:
    - xfce4-terminal

- name: create xfce config directory
  become: true
  become_user: "{{ username }}"
  file:
    path: "~/.config/xfce4/terminal/colorschemes"
    state: directory
  when: ansible_facts.packages['xfce4-terminal'] is defined

- name: install selected xfce themes
  become: true
  become_user: "{{ username }}"
  copy:
    src: "xfce-themes/"
    dest: "~/.config/xfce4/terminal/colorschemes"
  when: ansible_facts.packages['xfce4-terminal'] is defined

- name: configure xfce
  become: true
  become_user: "{{ username }}"
  template:
    src: xfce-terminalrc.j2
    dest: ~/.config/xfce4/terminal/terminalrc
  when: ansible_facts.packages['xfce4-terminal'] is defined
