---

- name: add repository GPG key for Yarn
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
  when: ansible_os_family == "Debian"

- name: add repository for Yarn
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
  when: ansible_os_family == "Debian"

- name: install Yarn
  become: yes
  ansible.builtin.apt:
    name: yarn
