---

- name: remove repository GPG key for Yarn
  become: true
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/yarn.asc
    state: absent
  when: ansible_os_family == "Debian"

# - name: add repository GPG key for Yarn
#   become: true
#   ansible.builtin.get_url:
#     url: https://dl.yarnpkg.com/debian/pubkey.gpg
#     dest: /etc/apt/trusted.gpg.d/yarn.asc
#   when: ansible_os_family == "Debian"
#   tags: never

- name: add repository for Yarn
  become: true
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/yarn.asc] https://dl.yarnpkg.com/debian/ stable main
    state: absent
  when: ansible_os_family == "Debian"

- name: install Yarn
  become: true
  ansible.builtin.apt:
    name: yarn
    state: absent
    purge: true
