---

- name: install sudo
  become: true
  ansible.builtin.apt:
    name: sudo

- name: configure sudo
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo	ALL=(ALL:ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: add {{ username }} to sudo group
  become: true
  user:
    name: "{{ username }}"
    append: true
    groups:
      - sudo

- name: deploy sudoers configuration
  become: true
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/zzz-custom
    validate: /usr/sbin/visudo -c %s
