---

- name: install sudo
  become: yes
  ansible.builtin.apt:
    name: sudo

- name: configure sudo
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo	ALL=(ALL:ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: add {{ username }} to sudo group
  become: yes
  user:
    name: "{{ username }}"
    append: yes
    groups:
      - sudo
