---

- name: install Hetzner CLI
  become: true
  apt:
    name: hcloud-cli
    state: latest
  register: hcloud_install

- name: hcloud completion configuration
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: "hcloud completion fish > {{ config.fish }}/completions/hetzner-cloud.fish"
  when:
  - hcloud_install.changed
  - ansible_facts.packages["fish"] is defined
