---

- name: install weechat and plugins
  become: yes
  ansible.builtin.apt:
    name:
    - weechat
    - python-notify2

- name: install weechat plugin notify
  become: yes
  become_user: "{{ username }}"
  get_url:
    url: https://weechat.org/files/scripts/notify.py
    dest: ~/.weechat/python/autoload/notify.py
  when: ansible_facts.packages['weechat'] is defined
