---

- name: check ruff releases
  uri:
    url: https://api.github.com/repos/astral-sh/ruff/releases/latest
    return_content: true
  register: releases

- name: set latest ruff version
  set_fact:
    ruff_latest_version: "{{ releases.json.tag_name }}"
  when: not ansible_check_mode

- name: check local ruff
  stat:
    path: /usr/local/bin/ruff
  register: ruff_stat

- name: check local ruff version
  command: /usr/local/bin/ruff --version
  register: ruff_version
  changed_when: false
  when: ruff_stat.stat.exists

- name: create temporary directory for install archive
  ansible.builtin.tempfile:
    state: directory
    suffix: ruff
  register: ruff_temp
  when:
    - not ansible_check_mode
    - not ruff_stat.stat.exists or ruff_latest_version not in ruff_version.stdout_lines[0]
  diff: false

- name: download ruff {{ releases.json.tag_name }}
  ansible.builtin.unarchive:
    dest: "{{ ruff_temp.path }}"
    src: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `linux-musl`) && contains(name, `x86_64`)].browser_download_url | [0]') }}"
    remote_src: true
    extra_opts:
    - --strip-components=1
  register: ruff_download
  diff: false
  when:
    - ruff_temp.path is defined

- name: install ruff {{ releases.json.tag_name }}
  become: true
  copy:
    src: "{{ ruff_temp.path }}/ruff"
    dest: "/usr/local/bin/ruff"
    remote_src: true
    mode: 0755
  when:
    - ruff_temp.path is defined
