---

- name: check pandoc latest release
  uri:
    url: https://api.github.com/repos/jgm/pandoc/releases/latest
    return_content: true
  register: last_release
  tags: system

- name: install or upgrade pandoc {{ last_release.json.tag_name }}
  become: true
  apt:
    deb: "{{ last_release.json |to_json|from_json| json_query('assets[?contains(name, `deb`) && contains(name, `amd64`)].browser_download_url | [0]') }}"
    state: present
  when:
    - not ansible_check_mode
    - ansible_facts.packages['pandoc'] is not defined or not ansible_facts.packages['pandoc'][0]['version'].startswith(last_release.json.tag_name)
  tags: system
