---

- name: set firefox package name
  set_fact:
    firefox_package: "firefox{% if not debian_unstable_is_active %}-esr{% endif %}"

# - name: set firefox package name for uninstall in case
#   set_fact:
#     firefox_uninstall_package: "firefox{% if debian_unstable_is_active %}-esr{% endif %}"

# - name: remove any previous firefox
#   become: true
#   ansible.builtin.apt:
#     name: "{{ firefox_uninstall_package }}"
#     state: absent

- name: install firefox
  become: true
  ansible.builtin.apt:
    name: firefox
    default_release: unstable
  when: debian_unstable_is_active

- name: install firefox-esr
  become: true
  ansible.builtin.apt:
    name: firefox-esr

- name: check browser preferences
  command: xdg-settings get default-web-browser
  register: browser_prefs
  changed_when: false

- name: set system browser preferences to use firefox
  become: true
  become_user: "{{ username }}"
  command: "xdg-settings set default-web-browser {{ firefox_package }}.desktop"
  when:
    - not ansible_check_mode
    - browser_prefs.stdout != firefox_package + ".desktop"

- name: list all firefox profiles
  become: true
  become_user: "{{ username }}"
  ansible.builtin.find:
    file_type: directory
    path: "~/.mozilla/firefox/"
    patterns: ["*.default*"]
  register: firefox_profiles

- name: set firefox preferences
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: user.js.j2
    dest: "{{ item.path }}/user.js"
  loop: "{{ firefox_profiles.files }}"
  when:
    - firefox_profiles is defined
    - not firefox_profiles.failed
