---
# Waiting for bug to fixed: https://github.com/ansible/ansible/pull/79518
# https://github.com/ansible/ansible/issues/64016

- name: check iA fonts files
  become: true
  ansible.builtin.stat:
    path: "/usr/local/share/fonts/iafonts/{{ item | urlsplit('path') | basename }}"
  loop:
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Variable/iAWriterDuoV-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Variable/iAWriterDuoV.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Variable/iAWriterMonoV-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Variable/iAWriterMonoV.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Variable/iAWriterQuattroV-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Variable/iAWriterQuattroV.ttf
  register: iafonts_stat

- name: create iA fonts directory
  become: true
  ansible.builtin.file:
    path: /usr/local/share/fonts/iafonts/
    state: directory

- name: install iA fonts
  become: true
  ansible.builtin.get_url:
    url: "{{ item.item }}"
    dest: "/usr/local/share/fonts/iafonts/{{ item.item | urlsplit('path') | basename }}"
    mode: 0644
    force: false
  when: not item.stat.exists
  loop: "{{ iafonts_stat.results }}"
  register: iafonts_downloaded
