---

- name: debug
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ fonts }}"


- name: install fonts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/share/fonts/{{ item | basename }}"
    mode: 0644
  loop: "{{ fonts }}"
  register: local_fonts
