---

- name: install iA Fonts
  include_tasks: iafonts.yml

- name: install monaspace Fonts
  include_tasks: monaspace.yml

- name: install fonts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/share/fonts/{{ item | basename }}"
    mode: 0644
  loop: "{{ fonts }}"
  register: local_fonts
  vars:
    fonts:
      - "Montserrat/Montserrat-Italic-VariableFont_wght.ttf"
      - "Montserrat/Montserrat-VariableFont_wght.ttf"
      - "Oswald/Oswald-VariableFont_wght.ttf"
      - "Source_Code_Pro/SourceCodePro-Italic-VariableFont_wght.ttf"
      - "Source_Code_Pro/SourceCodePro-VariableFont_wght.ttf"
      - "Source_Code_Pro/static/SourceCodePro-Black.ttf"
      - "Source_Code_Pro/static/SourceCodePro-BlackItalic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-Bold.ttf"
      - "Source_Code_Pro/static/SourceCodePro-BoldItalic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-ExtraBold.ttf"
      - "Source_Code_Pro/static/SourceCodePro-ExtraBoldItalic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-ExtraLight.ttf"
      - "Source_Code_Pro/static/SourceCodePro-ExtraLightItalic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-Italic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-Light.ttf"
      - "Source_Code_Pro/static/SourceCodePro-LightItalic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-Medium.ttf"
      - "Source_Code_Pro/static/SourceCodePro-MediumItalic.ttf"
      - "Source_Code_Pro/static/SourceCodePro-Regular.ttf"
      - "Source_Code_Pro/static/SourceCodePro-SemiBold.ttf"
      - "Source_Code_Pro/static/SourceCodePro-SemiBoldItalic.ttf"

- name: rebuild font cache
  become: true
  ansible.builtin.command: /usr/bin/fc-cache /usr/local/share/fonts
  when: iafonts_downloaded.changed or monaspace_local_version.changed or local_fonts.changed
