---

- name: install iA Fonts
  include_tasks: iafonts.yml

- name: install monaspace Fonts
  include_tasks: monaspace.yml

- name: rebuild font cache
  become: true
  ansible.builtin.command: /usr/bin/fc-cache /usr/local/share/fonts
  when: iafonts_downloaded.changed or monaspace_local_version.changed
