---

# Waiting for bug to fixed: https://github.com/ansible/ansible/pull/79518
# https://github.com/ansible/ansible/issues/64016

- name: install iA fonts
  become: true
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/usr/local/share/fonts/{{ item | urlsplit('path') | basename }}"
    mode: 0644
    force: false
  when: not ("/usr/local/share/fonts/{{ item | urlsplit('path') | basename }}") is exists
  loop:
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Static/iAWriterDuoS-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Variable/iAWriterDuoV-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duo/Variable/iAWriterDuoV.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duospace/TTF%20(PC)/iAWriterDuospace-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duospace/TTF%20(PC)/iAWriterDuospace-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duospace/TTF%20(PC)/iAWriterDuospace-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Duospace/TTF%20(PC)/iAWriterDuospace-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Static/iAWriterMonoS-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Variable/iAWriterMonoV-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Mono/Variable/iAWriterMonoV.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-Bold.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-BoldItalic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Static/iAWriterQuattroS-Regular.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Variable/iAWriterQuattroV-Italic.ttf
    - https://github.com/iaolo/iA-Fonts/raw/master/iA%20Writer%20Quattro/Variable/iAWriterQuattroV.ttf

- name: rebuild font cache
  become: true
  ansible.builtin.command: /usr/bin/fc-cache /usr/local/share/fonts