---

# For Audible, to extract audiobook to standard files and listen to it everywhere
# https://en.code-bude.net/2017/02/12/how-to-convert-audible-aax-files-to-mp3-in-linux/

- name: directory for audible tools
  become: true
  become_user: "{{ username }}"
  file:
    path: ~/audible
    state: directory

- name: install audible tools to easily move to non-DRM files
  become: true
  ansible.builtin.apt:
    name:
    - ffmpeg
    - libmp3lame0
    - mp4v2-utils

- name: install tools to extract Audible info
  become: true
  become_user: "{{ username }}"
  git:
    clone: true
    accept_hostkey: true
    dest: "~/audible/{{ item.dest }}/"
    repo: "{{ item.url }}"
    update: true
    verify_commit: false
  loop:
    - url: https://github.com/KrumpetPirate/AAXtoMP3.git
      dest: AAXtoMP3
    - url: https://github.com/inAudible-NG/audible-activator.git
      dest: audible-activator

