---

- name: install/upgrade pipx
  become: true
  pip:
    name: pipx
    state: latest

- name: install tools with pipx
  community.general.pipx:
    name: "{{ item.name }}"
    state: install
  loop: "{{ python_tools }}"

- name: install extra modules for python tools
  community.general.pipx:
    name: "{{ item.name }}"
    inject_packages: "{{ item.extra }}"
    state: inject
  loop: "{{ python_tools }}"
  when: item.extra is defined
