---

- name: install/upgrade pipx
  become: true
  pip:
    name: pipx
    state: latest

- name: pipx autocompletion
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: completion-pipx.zsh
    dest: "{{ config.zsh }}/python/completion.zsh"

- name: install tools with pipx
  community.general.pipx:
    name: "{{ item.name }}"
    state: install
  loop: "{{ python_tools }}"

- name: install extra modules for python tools
  community.general.pipx:
    name: "{{ item.name }}"
    inject_packages: "{{ item.extra }}"
    state: inject
  loop: "{{ python_tools }}"
  when: item.extra is defined

- name: include package task
  include_tasks: "{{ item.name }}.yml"
  when: "(item.name + '.yml') is file"
  loop: "{{ python_tools }}"