---
# Replacement for lsusb with nice output
- name: check cyme releases
  uri:
    url: https://api.github.com/repos/tuna-f1sh/cyme/releases/latest
    return_content: true
  register: latest_release

- name: install latest cyme
  become: true
  apt:
    deb: "{{ latest_release.json |to_json|from_json| json_query('assets[?contains(name, `amd64`) && contains(name, `deb`)].browser_download_url | [0]') }}"
    state: present
  when:
    - not ansible_check_mode
    - ansible_facts.packages['cyme'] is not defined or ansible_facts.packages['cyme'][0]['version'] != latest_release.json.tag_name
  tags: system
