---

- name: check kdrive local binary
  stat:
    path: "/usr/local/bin/kDrive.AppImage"
  register: kdrive_stat

- name: check kDrive version
  command: /usr/local/bin/kDrive --version
  register: kdrive_version
  when: kdrive_stat.stat.exists

- name: download kDrive app image
  become: true
  get_url:
    dest: "/usr/local/bin/kDrive.AppImage"
    url: "https://download.storage.infomaniak.com/drive/desktopclient/kDrive-{{ kdrive.version }}-amd64.AppImage"
    owner: root
    group: root
    mode: "0755"
  when:
    - not ansible_check_mode
    - not kdrive_stat.stat.exists or (kdrive.version.split('.')[:-1] | join('.')) not in kdrive_version.stdout_lines[0]

- name: link kDrive
  become: true
  file:
    state: link
    src: "/usr/local/bin/kDrive.AppImage"
    dest: /usr/local/bin/kDrive
  when: not ansible_check_mode
