---

# Install and configure a systemd service for Dropbox
# https://www.dropbox.com/install

- name: download Dropbox
  become: true
  when: ansible_os_family == "Debian"
  get_url:
    dest: /usr/bin/dropbox
    mode: 0755
    url: https://www.dropbox.com/download?dl=packages/dropbox.py
  register: dropbox_install

- name: configure a systemd service for Dropbox
  become: true
  template:
    src: dropbox.service.j2
    dest: /etc/systemd/system/dropbox@.service
  register: dropbox_service

- name: service daemon reload
  become: true
  systemd:
    daemon_reload: true
  when: dropbox_service.changed

- name: install dropbox daemon
  become: true
  become_user: "{{ username }}"
  command: dropbox start -i -y
  args:
    creates: "~/.dropbox-dist"
  when: dropbox_service.changed
  register: dropbox_daemon

- name: get link to activate account
  become: true
  become_user: "{{ username }}"
  command: dropbox status
  register: dropbox_status
  when: dropbox_daemon.changed

- name: dropbox activation link
  pause:
    prompt: "Open the link to activate this device: {{ dropbox_status.stdout }}"
  when: dropbox_daemon.changed

- name: enable systemd Dropbox service for {{ username }}
  become: true
  systemd:
    enabled: true
    name: "dropbox@{{ username }}.service"
    state: started
  when: dropbox_install is defined and dropbox_daemon is defined and dropbox_daemon.changed
