---

- name: install OpenConnect tool for Fortinet VPN
  become: true
  ansible.builtin.apt:
    pkg:
      - openconnect
      - network-manager-openconnect
      - network-manager-openconnect-gnome
