---

- name: install OpenConnect tool for Fortinet VPN
  become: true
  ansible.builtin.apt:
    pkg:
      - openconnect
      - network-manager-openconnect
      - network-manager-openconnect-gnome

- name: copy vpn function
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: "vpn-on.sh"
    dest: "~/bin/vpn-on"
    mode: 0755
