---

- name: install OpenFortiVPN
  become: true
  ansible.builtin.apt:
    pkg:
      - openfortivpn

- name: configure OpenFortiVPN
  became: true
  ansible.builtin.template:
    src: openfortivpn.conf.j2
    dest: /etc/openfortivpn/work