---

- import_tasks: fortinet.yml
  tags:
    - fortinet

- import_tasks: concourse.yml
  tags:
    - concourse

- import_tasks: keeper.yml
  tags:
    - keeper

- name: copy configurations
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: config.fish
      dest: "{{ config.fish }}/conf.d/work.fish"
    # - src: functions.fish
    #   dest: "{{ config.fish }}/functions/work.fish"
