---

- name: check Task releases
  uri:
    url: https://api.github.com/repos/go-task/task/releases/latest
    return_content: true
  register: releases
  tags: system

- name: install or upgrade Task {{ releases.json.name }}
  become: true
  apt:
    deb: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `deb`) && contains(name, `linux_amd64`)].browser_download_url | [0]') }}"
    state: present
  when:
    - not ansible_check_mode
    - ansible_facts.packages['task'] is not defined or not ansible_facts.packages['task'][0]['version'].startswith(releases.json.name)
  register: task_install
  tags: system

- name: Task completion configuration
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: "task --completion fish > {{ config.fish }}/completions/task.fish"
  when:
  - task_install.changed
  - ansible_facts.packages["fish"] is defined
