---

- name: install java packages
  become: true
  ansible.builtin.apt:
    name:
    - maven
    - openjdk-11-jdk
    - openjdk-14-jdk

- name: change default java alternatives
  become: true
  command: update-java-alternatives -s java-1.8.0-openjdk-amd64
  tags: never
