---

- name: apt cache update
  become: true
  apt:
    update_cache: true

- name: apt dist-upgrade
  become: true
  apt:
    upgrade: dist
  register: apt_upgrade

- name: show dist apt upgrade output
  debug:
    var: apt_upgrade
  when: apt_upgrade is defined

- name: install unattended-upgrades
  become: true
  apt: pkg=unattended-upgrades state=latest

- name: remove useless packages from the cache
  become: true
  apt:
    autoclean: true

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true
