---

- name: install udev rules for keyboardio Model 100
  become: true
  ansible.builtin.template:
    src: keyboardio.rules.j2
    dest: /etc/udev/rules.d/60-kaleidoscope.rules
  register: keyboardio_rules

- name: reload udev rules
  become: true
  ansible.builtin.command: /usr/bin/udevadm control --reload
  when: keyboardio_rules.changed

- name: trigger udev
  become: true
  ansible.builtin.command: /usr/bin/udevadm trigger
  when: keyboardio_rules.changed

- name: check if Chrysalis is already installed
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.stat:
    path: ~/bin/chrysalis
  register: chrysalis_stat

- name: check Chrysalis releases
  ansible.builtin.uri:
    url: https://api.github.com/repos/keyboardio/Chrysalis/releases/latest
    return_content: yes
  register: chrysalis_releases
  when: not chrysalis_stat.stat.exists

- name: download Chrysalis app image
  become: yes
  become_user: "{{ username }}"
  get_url:
    dest: "~/bin/Chrysalis.AppImage"
    url: "{{ chrysalis_releases.json |to_json|from_json| json_query('assets[?contains(name, `AppImage`)].browser_download_url | [0]') }}"
    mode: "0755"
  when:
    - not ansible_check_mode
    - not chrysalis_stat.stat.exists

- name: link Chrysalis
  become: yes
  become_user: "{{ username }}"
  file:
    state: link
    src: "~/bin/Chrysalis.AppImage"
    dest: ~/bin/chrysalis
  when:
    - not ansible_check_mode
    - not chrysalis_stat.stat.exists
