---

- name: install rust tools
  become: true
  ansible.builtin.apt:
    name:
    - cargo

- name: rust configuration directory
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "{{ config.zsh }}/rust"
    state: directory
  when: ansible_facts.packages["zsh"] is defined

- name: rust configuration
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: ansible_facts.packages[item.shell] is defined
  with_items:
  - src: env.zsh
    dest: "{{ config.zsh }}/rust/env.zsh"
    shell: zsh
  - src: env.fish
    dest: "{{ config.fish }}/conf.d/rust.fish"
    shell: fish
