---

- name: check obsidian releases
  ansible.builtin.uri:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
    return_content: true
  register: obsidian_release

- name: install or upgrade obsidian {{ obsidian_release.json.tag_name }}
  become: true
  ansible.builtin.apt:
    deb: "{{ obsidian_release.json |to_json|from_json| json_query('assets[?contains(name, `deb`) && contains(name, `amd64`)].browser_download_url | [0]') }}"
    state: present
  when:
    - not ansible_check_mode
    - ansible_facts.packages['obsidian'] is not defined or not ansible_facts.packages['obsidian'][0]['version'].startswith(obsidian_release.json.name)
