---

- name: add repository GPG key for mise
  become: true
  ansible.builtin.get_url:
    url:  https://mise.jdx.dev/gpg-key.pub
    dest: /etc/apt/trusted.gpg.d/mise.asc
  tags: never

- name: add repository for mise
  become: true
  ansible.builtin.apt_repository:
    state: absent
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/mise.asc] https://mise.jdx.dev/deb stable main
  tags: never

- name: remove repository GPG key for mise
  become: true
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/mise.asc
    state: absent

- name: remove mise
  become: true
  ansible.builtin.apt:
    pkg:
      - mise
    state: absent
