---

- name: install docker packages
  become: true
  ansible.builtin.apt:
    name:
    - docker.io

- name: install docker packages
  become: true
  ansible.builtin.apt:
    name:
    - docker-compose
    state: absent
