---

- name: include distribution based Docker installation
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: install docker compose plugin
  include_tasks: compose.yml

- name: install docker buildx plugin
  include_tasks: buildx.yml

- name: add {{ username }} to docker group
  become: yes
  user:
    name: "{{ username }}"
    append: yes
    groups:
      - docker
