---

- name: include distribution based Docker installation
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: add {{ username }} to docker group
  become: yes
  user:
    name: "{{ username }}"
    append: yes
    groups:
      - docker
