---

- name: add repository GPG key for Docker
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc

- name: add docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

- name: install docker packages
  become: true
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
