---

- name: configure sshd
  become: true
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart ssh

- name: add authorized ssh keys for root
  become: true
  authorized_key:
    key: https://github.com/marcaurele.keys
    comment: "github user key for marcaurele"
    state: present
    user: root
