---

- name: install inputplug
  become: yes
  ansible.builtin.apt:
    name:
    - inputplug

- name: create inputplug config directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: "~/.config/inputplug"
    state: directory

- name: install inputplug event script
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: input-event.j2
    dest: "~/.config/inputplug/input-event"
    mode: "0750"
  register: inputplug_script

- name: install service file for inputplug
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "~/.config/systemd/user/inputplug.service"
  register: inputplug_service

- name: service daemon reload
  become: yes
  become_user: "{{ username }}"
  systemd:
    daemon_reload: yes
    scope: user
  when: inputplug_service.changed or inputplug_script.changed

- name: activate inputplug service
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    enabled: yes
    state: started
    name: inputplug.service
    scope: user
