
- name: install gcalcli
  become: yes
  ansible.builtin.apt:
    name:
    - gcalcli

- name: configure default calendar
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: gcalclirc.j2
    dest: "~/.gcalclirc"

- name: install script for next meeting
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: next-meeting.j2
    dest: "~/bin/next-meeting"
    mode: "0750"

- name: install service file for next-meeting
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "~/.config/systemd/user/next-meeting.service"
  register: nextmeeting_service

- name: install service timer file for next-meeting
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: systemd.timer.j2
    dest: "~/.config/systemd/user/next-meeting.timer"
  register: nextmeeting_timer

- name: service daemon reload
  become: yes
  become_user: "{{ username }}"
  systemd:
    daemon_reload: yes
    scope: user
  when: nextmeeting_service.changed or nextmeeting_timer.changed

- name: configure next-meeting service
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    enabled: yes
    name: next-meeting.service
    scope: user

- name: configure next-meeting timer
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    enabled: yes
    name: next-meeting.timer
    state: started
    scope: user
