---

- name: remove balena-etcher
  become: true
  apt:
    name: "balena-etcher"
    state: absent

# - name: check balena-etcher latest release
#   uri:
#     url: https://api.github.com/repos/balena-io/etcher/releases/latest
#     return_content: true
#   register: etcher_release
#   tags: system

# - name: install or upgrade balena-etcher {{ etcher_release.json.name }}
#   become: true
#   apt:
#     deb: "{{ etcher_release.json |to_json|from_json| json_query('assets[?contains(name, `deb`) && contains(name, `amd64`)].browser_download_url | [0]') }}"
#     state: present
#   when:
#     - not ansible_check_mode
#     - ansible_facts.packages['balena-etcher'] is not defined or not ansible_facts.packages['balena-etcher'][0]['version'].startswith(etcher_release.json.name)
#   tags: system
