---

- name: install python packages
  become: yes
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip

- name: install some python packages through pip
  become: yes
  pip:
    name:
    - pipenv
    state: latest
