---

- name: install python packages
  become: true
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip
    - python3-venv

- name: python configuration directories
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ config.dir }}/pip"

- name: configure pip
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: pip.conf
    dest: ~/.config/pip/pip.conf
    mode: "0600"

- name: python configuration
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: ansible_facts.packages[item.shell] is defined
  with_items:
  - src: env.zsh
    dest: "{{ config.zsh }}/python/env.zsh"
    shell: zsh
  - src: env.fish
    dest: "{{ config.fish }}/conf.d/python.fish"
    shell: fish
