---

- name: install python packages
  become: true
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip
    - python3-venv
    - pipenv

- name: python configuration directories
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ config.zsh }}/python"
    - "{{ config.dir }}/pip"

- name: configure pip
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: pip.conf
    dest: ~/.config/pip/pip.conf
    mode: "0600"

- name: python configuration
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: env.zsh
    dest: "{{ config.zsh }}/python/env.zsh"
