---

- name: install python packages
  become: yes
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip

- name: install some python packages through pip
  become: yes
  pip:
    name:
    - pipenv
    state: latest

- name: python configuration
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: env.zsh
    dest: "{{ config.zsh }}/python/env.zsh"
