---

- name: install python packages
  become: yes
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip

- name: configure pip
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: pip.conf
    dest: ~/.config/pip/pip.conf
    mode: "0600"

- name: install some python packages through pip
  become: yes
  pip:
    name:
    - pipenv
    state: latest

- name: python configuration directory
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "{{ config.zsh }}/python"
    state: directory

- name: python configuration
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: env.zsh
    dest: "{{ config.zsh }}/python/env.zsh"
