---

- name: check sops latest release
  uri:
    url: https://api.github.com/repos/getsops/sops/releases/latest
    return_content: yes
  register: sops_release
  tags: system

- name: install or upgrade sops {{ sops_release.json.name }}
  become: yes
  apt:
    deb: "{{ sops_release.json |to_json|from_json| json_query('assets[?contains(name, `deb`) && contains(name, `amd64`)].browser_download_url | [0]') }}"
    state: present
  when:
    - not ansible_check_mode
    - ansible_facts.packages['sops'] is not defined or not ansible_facts.packages['sops'][0]['version'].startswith(sops_release.json.name)
  tags: system
