---
# Install script: https://deb.nodesource.com/setup_lts.x
- name: remove repository GPG key for NodeJS
  become: true
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/nodesource.asc
    state: absent

# - name: add repository GPG key for NodeJS
#   become: true
#   ansible.builtin.get_url:
#     url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#     dest: /etc/apt/trusted.gpg.d/nodesource.asc
#   tags: never

- name: add repository for NodeJS version for Debian
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_14.x {{ ansible_distribution_version }}  main"
    state: absent
  when: ansible_distribution == "Debian"

- name: add repository for NodeJS version for Ubuntu
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }}  main"
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: install NodeJS
  become: true
  apt:
    pkg:
      - nodejs
    state: absent
    purge: true
