---
# Install script: https://deb.nodesource.com/setup_lts.x
- name: add repository GPG key for NodeJS
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/trusted.gpg.d/nodesource.asc

- name: add repository for NodeJS version {{ nodejs.version }} for Debian
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs.version }} {{ ansible_distribution_version }}  main"
  when: ansible_distribution == "Debian"

- name: add repository for NodeJS version {{ nodejs.version }} for Ubuntu
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs.version }} {{ ansible_distribution_release }}  main"
  when: ansible_distribution == "Ubuntu"

- name: install NodeJS {{ nodejs.version }}
  become: true
  apt:
    pkg:
      - nodejs
    state: absent
    purge: true
