---

- name: check jwt-cli releases
  uri:
    url: https://api.github.com/repos/mike-engel/jwt-cli/releases/latest
    return_content: true
  register: releases

- name: set latest jwt-cli version
  set_fact:
    jwt_latest_version: "{{ releases.json.tag_name }}"
  when: not ansible_check_mode

- name: check local jwt-cli
  stat:
    path: /usr/local/bin/jwt
  register: jwt_stat

- name: check local jwt-cli version
  command: /usr/local/bin/jwt --version
  register: jwt_version
  changed_when: false
  when: jwt_stat.stat.exists

- name: create temporary directory for install archive
  ansible.builtin.tempfile:
    state: directory
    suffix: jwt
  register: jwt_temp
  when:
    - not ansible_check_mode
    - not jwt_stat.stat.exists or jwt_latest_version not in jwt_version.stdout_lines[0]
  diff: false

- name: download jwt-cli {{ releases.json.tag_name }}
  ansible.builtin.unarchive:
    dest: "{{ jwt_temp.path }}"
    src: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `linux-musl`) && contains(name, `tar.gz`)].browser_download_url | [0]') }}"
    remote_src: true
  register: jwt_download
  diff: false
  when:
    - jwt_temp.path is defined

- name: install jwt-cli {{ releases.json.tag_name }}
  become: true
  copy:
    src: "{{ jwt_temp.path }}/jwt"
    dest: "/usr/local/bin/jwt"
    remote_src: true
    mode: 0755
  when:
    - jwt_temp.path is defined
