---

- name: configuring APT sources
  become: true
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  register: apt_source
  tags: system, root

- name: set package preferences between testing and unstable
  become: true
  template:
    src: apt-preferences.j2
    dest: /etc/apt/preferences.d/apt-default.pref
  tags: system, root

- name: update package cache
  become: true
  apt:
    update_cache: true
  when: apt_source.changed
  tags: system, root

- name: install required packages for playbook
  become: true
  apt:
    name:
      - apt-transport-https
      - curl
      - gpg
      - python3-apt
      - software-properties-common
      - wget
  tags: system, root
