---
- name: configuring APT sources
  become: true
  template:
    src: debian.sources
    dest: /etc/apt/sources.list.d/debian.sources
  register: apt_source
  when: ansible_distribution == 'Debian'
  tags: system, root

- name: set package preferences between testing and unstable
  become: true
  template:
    src: apt-preferences.j2
    dest: /etc/apt/preferences.d/apt-default.pref
  when: ansible_distribution == 'Debian'
  tags: system, root

- name: update package cache
  become: true
  apt:
    update_cache: true
  when: apt_source.changed
  tags: system, root

- name: install required packages for playbook
  become: true
  apt:
    name:
      - apt-transport-https
      - curl
      - python3-apt
      - sequoia-chameleon-gnupg
      - snapd
      - wget
  tags: system, root
