---

- name: remove ZSH
  become: true
  ansible.builtin.apt:
    name:
    - zplug
    - zsh
    state: absent

# - name: install ZSH
#   become: true
#   ansible.builtin.apt:
#     name:
#     - zplug
#     - zsh

- name: remove ZSH config data
  become: true
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ config.zsh }}"
  - "~/.zshenv"
  - "~/.zsh"
  - "~/.zshrc"
  # - "~/.zsh_history"
  tags: user

# - name: create ZSH alias config directory
#   become: true
#   become_user: "{{ username }}"
#   file:
#     path: "{{ config.zsh }}"
#     state: directory
#   tags: user

# - name: copy ZSH config files
#   become: true
#   become_user: "{{ username }}"
#   copy:
#     src: "."
#     dest: "{{ config.zsh }}/"
#     mode: preserve
#   tags: user

# - name: install config dot files
#   become: true
#   become_user: "{{ username }}"
#   template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: "{{ item.mode | default('0644')}}"
#   loop:
#     - src: zshrc.j2
#       dest: "~/.zshrc"
#   tags: user
