---

- name: install ZSH
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - zplug
    - zsh

- name: create ZSH alias config directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: "~/.zsh_config"
    state: directory
  tags: user

- name: copy ZSH config files
  become: yes
  become_user: "{{ username }}"
  copy:
    src: "."
    dest: "~/.zsh_config/"
    mode: preserve
  tags: user

- name: install config dot files
  become: yes
  become_user: "{{ username }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644')}}"
  loop:
    - src: zshrc.j2
      dest: "~/.zshrc"
  tags: user

- name: change {{ username }} shell to ZSH
  become: yes
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"
  tags: user, root
